export { default as ElevaLogo } from './icons/eleva-logo.svg';
export { default as AdaraBed } from './adara-bed-cropped.jpg';
// export { default as DelayedPayment } from './icons/delay-payment-icon.png';
// export { default as Delivery } from './icons/delivery-icon.png';
// export { default as ProductReturns } from './icons/product-return-icon-resized.png';
// export { default as Swatch } from './icons/swatch-icon-resized.png';
export { default as DelayedPayment } from './icons/delayed-payment-cropped.png';
export { default as Delivery } from './icons/delivery-cropped.png';
export { default as ProductReturns } from './icons/product-return-cropped.png';
export { default as Swatch } from './icons/swatch-cropped.png';
export { default as instaImage0 } from './instagram-reel/image_0.jpg';
export { default as instaImage1 } from './instagram-reel/image_1.jpg';
export { default as instaImage2 } from './instagram-reel/image_2.jpg';
export { default as instaImage3 } from './instagram-reel/image_3.jpg';
export { default as instaImage4 } from './instagram-reel/image_4.jpg';
export { default as instaImage5 } from './instagram-reel/image_5.jpg';
export { default as instaImage6 } from './instagram-reel/image_6.jpg';
export { default as instaImage7 } from './instagram-reel/image_7.jpg';
export { default as instaImage8 } from './instagram-reel/image_8.jpg';
export { default as instaImage9 } from './instagram-reel/image_9.jpg';
export { default as instaImage10 } from './instagram-reel/image_10.jpg';
export { default as instaImage11 } from './instagram-reel/image_11.jpg';
export { default as instaImage12 } from './instagram-reel/image_12.jpg';
export { default as outdoorColImage } from './home-photos/outdoor-collection.jpg';
export { default as lightingImage } from './home-photos/lighting.jpg';
export { default as beddingImage } from './home-photos/bedding.jpg';
